require_relative "resolvers/line_item_resolver"
require_relative "resolvers/order_resolver"
require_relative "resolvers/product_resolver"
require_relative "resolvers/user_resolver"
require_relative "resolvers/variant_resolver"
require_relative "resolvers/classification_resolver"
require_relative "resolvers/taxon_resolver"
